# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
      home_icon: "~"
      style: full
    template: "<#83a598>┏ </><#ffaf00>{{ .Path }} </>"
    type: path
    style: plain
  - properties:
      cache_duration: none
      fetch_version: true
    template:  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}
    foreground: "#689d6a"
    powerline_symbol: 
    type: node
    style: plain
  - properties:
      cache_duration: none
    template: " \ue70c {{ .Full }} "
    foreground: "#83a598"
    powerline_symbol: 
    type: dotnet
    style: plain
  - properties:
      cache_duration: none
      fetch_version: true
    template:  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}
    foreground: "#689d6a"
    powerline_symbol: 
    type: go
    style: plain
  - properties:
      cache_duration: none
      display_mode: files
      fetch_virtual_env: false
    template:  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}
    foreground: "#b16286"
    powerline_symbol: 
    type: python
    style: plain
  - properties:
      cache_duration: none
      display_mode: files
      fetch_version: true
    template:  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}
    foreground: "#b16286"
    powerline_symbol: 
    type: ruby
    style: plain
  - properties:
      cache_duration: none
      display_mode: files
      fetch_version: false
    template: "\uf0e7  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    foreground: "#83a598"
    powerline_symbol: 
    type: azfunc
    style: plain
  - properties:
      cache_duration: none
      display_default: false
    template: "\ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
    foreground: "#ebdbb2"
    powerline_symbol: 
    type: aws
    style: plain
    background_templates:
    - "{{if contains \"default\" .Profile}}#d65d0e{{end}}"
    - "{{if contains \"jan\" .Profile}}#fe8019{{end}}"
- type: prompt
  alignment: right
  segments:
  - properties:
      branch_max_length: 25.0
      cache_duration: none
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
    trailing_diamond: 
    template: " <#83a598>[</>{{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }}<#83a598>]</>"
    foreground: "#b8bb26"
    type: git
    style: plain
    foreground_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#fb4934{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#d79921{{ end }}"
    - "{{ if gt .Ahead 0 }}#d79921{{ end }}"
    - "{{ if gt .Behind 0 }}#d79921{{ end }}"
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: "\ue3bf "
    foreground: "#fb4934"
    type: root
    style: plain
  - properties:
      always_enabled: true
      cache_duration: none
    template: "<#83a598>┖</>#"
    foreground: "#83a598"
    type: exit
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}#fb4934{{ end }}"
  newline: true
version: 3
final_space: true
