#!/usr/bin/env bash

declare location="${0%/*}"

source "$location/lib/slugify"
source "$location/lib/yyyymmdd"

set -eo pipefail
shopt -s extglob

die() { echo "$1" >&2; exit 1; }

# Strict context check
[[ -n "$CONTEXT_POST_PATH" ]]     || die "No writing context. Run: cch <context>"
[[ -n "$CONTEXT_POST_TEMPLATE" ]] || die "CONTEXT_POST_TEMPLATE not set for this context."

render_template() {
  local title="$1"
  shift
  local tags=("$@")
  local date
  date=$(yyyymmdd)

  while IFS= read -r line; do
    line="${line//__TITLE__/$title}"
    line="${line//__DATE__/$date}"
    line="${line//__CATEGORY__/${tags[1]:-uncategorized}}"
    printf '%s\n' "$line"
  done < "$CONTEXT_POST_TEMPLATE"

  if [[ "${#tags[@]}" -gt 1 ]]; then
    for tag in "${tags[@]:1}"; do
      printf '  - %s\n' "$tag"
    done
  fi
}

generate_filename() {
  local title=$1
  echo "$CONTEXT_POST_PATH/$(yyyymmdd)-$(slugify "$title").md"
}

main() {
  local title filename

  [[ -n $TMUX ]] || die "tmux isn't running"
  : "${1:?Specify post title}"

  filename="$(generate_filename "$1")"

  [[ ! -f "$filename" ]] && render_template "$@" > "$filename"

  cd "$CONTEXT_POST_PATH"
  nvim "$filename"
}

main "$@"
