#!/usr/bin/env bash

declare location="${0%/*}"

source "$location/lib/yyyymmdd"

FILENAME=$(yyyymmdd).md
FILEPATH="$WRITING_PATH/DailyNotes/$FILENAME"

createDaily() {
  cat > "$FILEPATH" << EOF
# Daily Note: $(date "+%A %d. %B %Y")

## Goals
-

## Tasks
- [ ]

## Reflections
-

## Accomplishments
-

## Braindump
-

EOF

}

if [ -f "$FILEPATH" ]; then
  $EDITOR "$FILEPATH"
else
  # Create new daily note
  createDaily
  $EDITOR "$FILEPATH"
fi
